id: A78738384
title: Aspiration for the Maṇi Reciter of Kham
type: translation
pechas:
- I2962910C
- I77191715
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:58:42.990662
  last_modified_at: 2023-01-04 11:58:42.990668
  collections:
  - Gyalse Tokme Zangpo
  - Works of Tibetan Masters
alignment_to_base:
  I2962910C/6A25: F549
  I77191715/CEEE: F549
